# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'


# 去掉由pod引入的第三方库的警告，需要更新命令才生效
inhibit_all_warnings!

# pod 快速更新方法
# pod update --verbose --no-repo-update


target 'BAQMUIDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for BAQMUIDemo
    pod 'QMUIKit', '~> 1.7.2'
#    pod 'XHLaunchAd'
    pod 'AFNetworking'
    
    pod 'BANetManager'
    pod 'BAButton'
    pod 'BAAlert'
#    pod 'BAPickView'
    pod 'BATouchID'
    pod 'BATextView'
    pod 'BATextField'
    pod 'BAGridView'
    pod 'BAAlertController'
    pod 'BAPrivacyManager'


    # 网易云信 SDK (NIM SDK) 为移动应用提供完善的 IM 开发框架，屏蔽其内部复杂细节，对外提供较为简洁的 API 接口，方便第三方应用快速集成 IM 功能。SDK 兼容 iOS 7.0+ ，Demo 兼容 iOS 8.0+
#    pod 'NIMSDK'

    pod 'YYModel'
    pod 'YYCategories'
    
    pod 'YYImage'
    pod 'YYWebImage'
    # 网络或本地 多张图片浏览 控制器 MWPhotoBrowser (2.1.2)
    pod 'MWPhotoBrowser'

#    pod 'SDWebImage', '~> 4.0.0-beta2'

    # PPGetAddressBook对AddressBook框架(iOS9之前)和Contacts框架(iOS9之后)做了对应的封装处理;
    
    # 支持一句代码获取按联系人姓名首字拼音A~Z排序(重点:已处理姓名所有字符的排序问题,排序更准确!);
    
    # 支持一句代码获取原始顺序的联系人,未分组,可自行处理;
    # 已对号码中的"+86","-","()",空号和联系人姓名空白做了处理,不会出现因为数据源NULL导致程序crash的问题;
    # 对姓"长","沈","厦","地","冲"多音字进行优化处理.
    pod 'PPGetAddressBook'
    
    # 内存泄露检测工具
    pod 'MLeaksFinder'
    
    # 空数据的处理
    pod 'NullSafe'
    
    # 为滚动控件（UIScrollView, UITableView, UICollectionView）添加头部脚部刷新UI
    pod 'MJRefresh'
    
    # 空数据 的三方库
    pod 'DZNEmptyDataSet'

    # 离屏渲染，切边角
#    pod 'JMRoundedCorner', :git => 'https://github.com/raozhizhen/JMRoundedCorner.git', :tag => '1.9.2'

    # 数据库 sqlite
    pod 'FMDB'

    # ReactiveObjC包含RAC 2原来包含的全部代码
#    pod 'ReactiveObjC'

    pod 'NJKWebViewProgress'
    pod 'MBProgressHUD'
    pod 'SVProgressHUD', '~> 2.0.3'
    pod 'FDFullscreenPopGesture'
    pod 'FBMemoryProfiler'
    pod 'LBXAlertAction'
    pod 'ZYCornerRadius', git:'https://github.com/liuzhiyi1992/ZYCornerRadius.git',tag:'0.9.1'
#    pod 'SDCycleScrollView'

end

#Last login: Thu Jun 29 09:47:17 on ttys005

#- AFNetworking, 3.1.0
#- BAAlert, 1.2.2
#- BAAlertController, 1.0.1
#- BAButton, 2.5.4
#- BAGridView, 1.0.5
#- BANetManager, 2.2.2
#- BAPickView, 1.0.6
#- BATextView, 1.0.1
#- BATouchID, 1.0.1
#- DACircularProgress, 2.3.1
#- DZNEmptyDataSet, 1.8.1
#- FBAllocationTracker, 0.1.5
#- FBMemoryProfiler, 0.1.3
#- FBRetainCycleDetector, 0.1.3
#- FDFullscreenPopGesture, 1.1
#- FMDB, 2.7.2
#- LBXAlertAction, 1.0.3
#- MBProgressHUD, 0.9.2
#- MJRefresh, 3.1.12
#- MLeaksFinder, 0.2.1
#- MWPhotoBrowser, 2.1.2
#- NJKWebViewProgress, 0.2.3
#- NullSafe, 1.2.2
#- PPGetAddressBook, 0.2.8
#- QMUIKit, 1.7.2
#- SDWebImage, 3.8.2
#- SVProgressHUD, 2.0.4
#- YYCache, 1.0.4
#- YYCategories, 1.0.4
#- YYImage, 1.0.4
#- YYModel, 1.0.4
#- YYWebImage, 1.0.5
#- ZYCornerRadius, 0.8.1

#注释：更新时间 Last login: Sat Jun  3 14:01:27 on ttys003
#- AFNetworking, 3.1.0
#- BAAlert, 1.1.9
#- BAButton, 2.4.2
#- BANetManager, 2.2.2
#- BAPickView, 1.0.3
#- BATextView, 1.0.1
#- BATouchID, 1.0.1
#- DACircularProgress, 2.3.1
#- DZNEmptyDataSet, 1.8.1
#- FBAllocationTracker, 0.1.5
#- FBMemoryProfiler, 0.1.3
#- FBRetainCycleDetector, 0.1.3
#- FDFullscreenPopGesture, 1.1
#- FMDB, 2.6.2
#- LBXAlertAction, 1.0.3
#- MBProgressHUD, 0.9.2
#- MJRefresh, 3.1.12
#- MLeaksFinder, 0.2.1
#- MWPhotoBrowser, 2.1.2
#- NJKWebViewProgress, 0.2.3
#- NullSafe, 1.2.2
#- PPGetAddressBook, 0.2.8
#- QMUIKit, 1.7.1
#- SDWebImage, 3.8.2
#- SVProgressHUD, 2.0.4
#- YYCache, 1.0.4
#- YYCategories, 1.0.4
#- YYImage, 1.0.4
#- YYModel, 1.0.4
#- YYWebImage, 1.0.5
#- ZYCornerRadius, 0.8.1


#注释：更新时间 Last login: Sat May 27 16:07:09 on ttys004

#- AFNetworking, 3.1.0
#- BAAlert, 1.1.9
#- BAButton, 2.3.2
#- BANetManager, 2.2.2
#- BAPickView, 1.0.2
#- BATouchID, 1.0.1
#- DACircularProgress, 2.3.1
#- DZNEmptyDataSet, 1.8.1
#- FBAllocationTracker, 0.1.5
#- FBMemoryProfiler, 0.1.3
#- FBRetainCycleDetector, 0.1.3
#- FDFullscreenPopGesture, 1.1
#- FMDB, 2.6.2
#- LBXAlertAction, 1.0.3
#- MBProgressHUD, 0.9.2
#- MJRefresh, 3.1.12
#- MLeaksFinder, 0.2.1
#- MWPhotoBrowser, 2.1.2
#- NJKWebViewProgress, 0.2.3
#- NullSafe, 1.2.2
#- PPGetAddressBook, 0.2.8
#- QMUIKit, 1.6.0
#- SDWebImage, 3.8.2
#- SVProgressHUD, 2.0.4
#- YYCache, 1.0.4
#- YYCategories, 1.0.4
#- YYImage, 1.0.4
#- YYModel, 1.0.4
#- YYWebImage, 1.0.5
#- ZYCornerRadius, 0.8.1

#注释：更新时间 Last login: Wed May 17 11:24:52 on console

#- AFNetworking, 3.1.0
#- BAAlert, 1.1.8
#- BAButton, 2.2.1
#- BANetManager, 2.2.2
#- BAPickView, 1.0.0
#- DACircularProgress, 2.3.1
#- DZNEmptyDataSet, 1.8.1
#- FBAllocationTracker, 0.1.5
#- FBMemoryProfiler, 0.1.3
#- FBRetainCycleDetector, 0.1.3
#- FDFullscreenPopGesture, 1.1
#- FMDB, 2.6.2
#- LBXAlertAction, 1.0.3
#- MBProgressHUD, 0.9.2
#- MJRefresh, 3.1.12
#- MLeaksFinder, 0.2.1
#- MWPhotoBrowser, 2.1.2
#- NJKWebViewProgress, 0.2.3
#- NullSafe, 1.2.2
#- PPGetAddressBook, 0.2.8
#- QMUIKit, 1.6.0
#- SDWebImage, 3.8.2
#- SVProgressHUD, 2.0.4
#- YYCache, 1.0.4
#- YYCategories, 1.0.4
#- YYImage, 1.0.4
#- YYModel, 1.0.4
#- YYWebImage, 1.0.5
#- ZYCornerRadius, 0.8.1

#注释：更新时间 Last login: Tue May  9 13:00:28 on ttys002

#- AFNetworking, 3.1.0
#- BAAlert, 1.1.4
#- BAButton, 2.2.1
#- BANetManager, 2.2.2
#- DACircularProgress, 2.3.1
#- DSAlert-OC, 1.0.8
#- DZNEmptyDataSet, 1.8.1
#- FBAllocationTracker, 0.1.5
#- FBMemoryProfiler, 0.1.3
#- FBRetainCycleDetector, 0.1.3
#- FDFullscreenPopGesture, 1.1
#- FMDB, 2.6.2
#- LBXAlertAction, 1.0.3
#- MBProgressHUD, 0.9.2
#- MJRefresh, 3.1.12
#- MLeaksFinder, 0.2.1
#- MWPhotoBrowser, 2.1.2
#- NJKWebViewProgress, 0.2.3
#- NullSafe, 1.2.2
#- PPGetAddressBook, 0.2.8
#- QMUIKit, 1.5.2
#- SDWebImage, 3.8.2
#- SVProgressHUD, 2.0.4
#- YYCache, 1.0.4
#- YYCategories, 1.0.4
#- YYImage, 1.0.4
#- YYModel, 1.0.4
#- YYWebImage, 1.0.5
#- ZYCornerRadius, 0.8.1

#注释：更新时间 Last login: Thu May  4 16:50:20 on ttys003

#- AFNetworking, 3.1.0
#- BAButton, 2.2.1
#- BANetManager, 2.2.2
#- DACircularProgress, 2.3.1
#- DZNEmptyDataSet, 1.8.1
#- FBAllocationTracker, 0.1.5
#- FBMemoryProfiler, 0.1.3
#- FBRetainCycleDetector, 0.1.3
#- FDFullscreenPopGesture, 1.1
#- FMDB, 2.6.2
#- LBXAlertAction, 1.0.3
#- MBProgressHUD, 0.9.2
#- MJRefresh, 3.1.12
#- MLeaksFinder, 0.2.1
#- MWPhotoBrowser, 2.1.2
#- NJKWebViewProgress, 0.2.3
#- NullSafe, 1.2.2
#- PPGetAddressBook, 0.2.8
#- QMUIKit, 1.5.2
#- SDWebImage, 3.8.2
#- SVProgressHUD, 2.0.4
#- YYCache, 1.0.4
#- YYCategories, 1.0.4
#- YYImage, 1.0.4
#- YYModel, 1.0.4
#- YYWebImage, 1.0.5
#- ZYCornerRadius, 0.8.1

#注释：更新时间 Last login: Thu May  4 08:49:00 on ttys001

#- AFNetworking, 3.1.0
#- BAButton, 2.2.1
#- BANetManager, 2.2.2
#- DZNEmptyDataSet, 1.8.1
#- FBAllocationTracker, 0.1.5
#- FBMemoryProfiler, 0.1.3
#- FBRetainCycleDetector, 0.1.3
#- FDFullscreenPopGesture, 1.1
#- FMDB, 2.6.2
#- LBXAlertAction, 1.0.3
#- MBProgressHUD, 1.0.0
#- MJRefresh, 3.1.12
#- MLeaksFinder, 0.2.1
#- MWPhotoBrowser, 0.0.1
#- NJKWebViewProgress, 0.2.3
#- NullSafe, 1.2.2
#- PPGetAddressBook, 0.2.8
#- QMUIKit, 1.5.1
#- ReactiveObjC, 3.0.0
#- SDCycleScrollView, 1.66
#- SDWebImage, 4.0.0
#- SVProgressHUD, 2.0.4
#- YYCache, 1.0.4
#- YYCategories, 1.0.4
#- YYImage, 1.0.4
#- YYModel, 1.0.4
#- YYWebImage, 1.0.5

#注释：更新时间 Last login: Wed May  3 16:50:00 on ttys001

#- AFNetworking, 3.1.0
#- BAButton, 2.2.1
#- BANetManager, 2.2.2
#- DACircularProgress, 2.3.1
#- DZNEmptyDataSet, 1.8.1
#- FBAllocationTracker, 0.1.5
#- FBMemoryProfiler, 0.1.3
#- FBRetainCycleDetector, 0.1.3
#- FDFullscreenPopGesture, 1.1
#- FMDB, 2.6.2
#- MBProgressHUD, 0.9.2
#- MJRefresh, 3.1.12
#- MLeaksFinder, 0.2.1
#- MWPhotoBrowser, 2.1.2
#- NJKWebViewProgress, 0.2.3
#- NullSafe, 1.2.2
#- PPGetAddressBook, 0.2.8
#- QMUIKit, 1.5.1
#- ReactiveObjC, 3.0.0
#- SDWebImage, 3.8.2
#- SVProgressHUD, 2.0.4
#- YYCache, 1.0.4
#- YYCategories, 1.0.4
#- YYImage, 1.0.4
#- YYModel, 1.0.4
#- YYWebImage, 1.0.5

#注释：更新时间 Last update: Mar 20 16:18:23 on console

#- AFNetworking, 3.1.0
#- DACircularProgress, 2.3.1
#- DZNEmptyDataSet, 1.8.1
#- FBRetainCycleDetector, 0.1.3
#- FMDB, 2.6.2
#- MBProgressHUD, 0.9.2
#- MJRefresh, 3.1.12
#- MLeaksFinder, 0.2.1
#- MWPhotoBrowser, 2.1.2
#- NIMSDK, 3.5.0
#- NullSafe, 1.2.2
#- PPGetAddressBook, 0.2.8
#- QMUIKit, 1.3.4
#- ReactiveObjC, 2.1.2
#- SDWebImage, 3.8.2
#- YYCategories, 1.0.4
#- YYModel, 1.0.4



