# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'


# 去掉由pod引入的第三方库的警告，需要更新命令才生效
inhibit_all_warnings!

# pod 快速更新方法
# pod update --verbose --no-repo-update


target 'BAQMUIDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for BAQMUIDemo
    pod 'QMUIKit'
#    pod 'XHLaunchAd'
    pod 'AFNetworking'
    
    pod 'YYModel'
    pod 'YYCategories'
    
# 链接以下 frameworks:
#    UIKit
#    CoreFoundation
#    QuartzCore
#    AssetsLibrary
#    ImageIO
#    Accelerate
#    MobileCoreServices
#    sqlite3
#    libz
#    pod 'YYWebImage', :git => 'https://github.com/raozhizhen/YYWebImage.git', :tag => '1.0.5'
    # 网络或本地 多张图片浏览 控制器 MWPhotoBrowser (2.1.2)
    pod "MWPhotoBrowser"

#    pod 'SDWebImage', '~> 4.0.0-beta2'

    # PPGetAddressBook对AddressBook框架(iOS9之前)和Contacts框架(iOS9之后)做了对应的封装处理;
    
    # 支持一句代码获取按联系人姓名首字拼音A~Z排序(重点:已处理姓名所有字符的排序问题,排序更准确!);
    
    # 支持一句代码获取原始顺序的联系人,未分组,可自行处理;
    # 已对号码中的"+86","-","()",空号和联系人姓名空白做了处理,不会出现因为数据源NULL导致程序crash的问题;
    # 对姓"长","沈","厦","地","冲"多音字进行优化处理.
    pod 'PPGetAddressBook'
    
    # 内存泄露检测工具
    pod 'MLeaksFinder'
    
    # 空数据的处理
    pod 'NullSafe'
    
    # 为滚动控件（UIScrollView, UITableView, UICollectionView）添加头部脚部刷新UI
    pod 'MJRefresh'
    
    # 空数据 的三方库
    pod 'DZNEmptyDataSet'

    # 离屏渲染，切边角
#    pod 'JMRoundedCorner', :git => 'https://github.com/raozhizhen/JMRoundedCorner.git', :tag => '1.9.2'

    # 数据库 sqlite
    pod 'FMDB'

end

#注释：更新时间 Last login: Tue Feb 21 15:38:18 on ttys000

#- AFNetworking, 3.1.0
#- DACircularProgress, 2.3.1
#- DZNEmptyDataSet, 1.8.1
#- FBRetainCycleDetector, 0.1.3
#- MBProgressHUD, 0.9.2
#- MJRefresh, 3.1.12
#- MLeaksFinder, 0.2.1
#- MWPhotoBrowser, 2.1.2
#- NullSafe, 1.2.2
#- PPGetAddressBook, 0.2.8
#- QMUIKit, 1.3.0
#- SDWebImage, 3.8.2
#- YYCache, 1.0.4
#- YYCategories, 1.0.4
#- YYImage, 1.0.4
#- YYModel, 1.0.4
#- YYWebImage, 1.0.5



